# cdkr: Closed Domain Knowledge Retrieval
task_type: mcq
system_prompt: >
  You are a medical expert. Answer the following multiple choice
  question by selecting the single best answer. Respond with only
  the answer letter and nothing else.
fewshot_header: "Here are some examples:\n\n"
user_turn_template: >-
  Now answer the following question:

  Question: {{ question }}

  Options:
  {% for key, value in options.items() %}
  {{ key }}: {{ value }}
  {% endfor %}

  Answer:
fewshot_template: >-
  Question: {{ question }}

  Options:
  {% for key, value in options.items() %}
  {{ key }}: {{ value }}
  {% endfor %}

  Answer: {{ answer_idx }}
