source:
  hub_path: "zou-lab/MedCaseReasoning"

splits:
  eval: "test"
  fewshot: "val"

schema: "GenerativeSample"

mapping:
  question: "case_prompt"
  ref_reasoning: "diagnostic_reasoning"
  answer: "final_diagnosis"
  metadata:
    pmcid: "pmcid"
    title: "title"
    journal: "journal"
    article_link: "article_link"