source:
  data_files: "https://huggingface.co/datasets/bigbio/meqsum/resolve/refs%2Fconvert%2Fparquet/meqsum_bigbio_t2t/train/0000.parquet"

splits:
  eval: "train[95%:]"
  fewshot: "train[:-5%]"

schema: "GenerativeSample"

mapping:
  id: "id"
  question: "text_1"
  answer: "text_2"