# configs/pubmed_summarization.yaml
dataset: "ccdv/pubmed-summarization"
subset: "document"
task_type: "generation"
schema: "GenerativeSample"
eval_split: "test[:1000]"
fewshot_split: "train[:1000]"

mapping:
  question: "article"
  answer: "abstract"