source:
  hub_path: "GBaker/MedQA-USMLE-4-options"

splits:
  eval: "test"
  fewshot: "train"

schema: "MCQSample"

mapping:
  question: "question"
  options: "options"
  answer_idx: "answer_idx"
  grouping:
    meta_info: "meta_info"