source:
  name: "medxpertqa"
  hub_path: "TsinghuaC3I/MedXpertQA"
  subset: "Text"

splits:
  eval: "test"
  fewshot: "dev"

schema: "MCQSample"

mapping:
  id: "id"
  question: "question"
  options: "options"
  answer_idx: "label"
  grouping:
    body_system: "body_system"
  metadata:
    medical_task: "medical_task"
    question_type: "question_type"