source:
  hub_path: "ccdv/pubmed-summarization"
  subset: "document"

splits:
  eval: "test[:1000]"
  fewshot: "train[:1000]"

schema: "GenerativeSample"

mapping:
  question: "article"
  answer: "abstract"